# GENERAL
UNDEFINED = None

# DATABASE
DB_PATH = 'data/glide_db.db'

# TITLE OF GAME
TITLE = 'Glide game'

# FONTS
FONT_DROID = 'font/DroidSansJapanese.ttf'
FONT_ROB_LIGHT = 'font/Roboto-Light.ttf'
FONT_ROB_THIN = 'Roboto-Thin.ttf'

# FONT_SIZE
FONT_TWENTY_SIZE = 20
FONT_THIRTY_SIZE = 30
FONT_FORTY_SIZE = 40
FONT_SIZE_FIFTY = 50
FONT_SIZE_ONE_H_TWENTY = 120

# CONST (NAMES BALLS)
RED = 'red'
BLUE = 'blue'
# COLORS (RGB)
BLACK_COLOR = (0, 0, 0)
RED_COLOR = (255, 0, 0)
BLUE_COLOR = (0, 0, 255)
DEEP_GRAY = (54, 54, 54)
WHITE_COLOR = (255, 255, 255)
RED_TRAIL_COLOR_1 = (255, 55, 0)
RED_TRAIL_COLOR_2 = (255, 85, 55)
RED_TRAIL_COLOR_3 = (255, 40, 40)
BLUE_TRAIL_COLOR_1 = (0, 170, 240)
BLUE_TRAIL_COLOR_2 = (15, 135, 255)
BLUE_TRAIL_COLOR_3 = (0, 190, 255)
DELETE_WALL_TRACE_COLOR = [30, 30, 30]
START_WALL_TRACE_COLOR = [90, 90, 90]
COL_STEP_WALL_TRACES = 15

# NAMES OF IMAGES
ICON_IMG = 'icon.jpg'
RED_CIRCLE_IMG = 'circles_skins/red_circle.png'
BLUE_CIRCLE_IMG = 'circles_skins/blue_circle.png'
COINS_SHEET = "animation-coins.png"
MENU_IMG = "menu.png"
MOUSE_PNG = 'mouse.png'
# IMAGES FORMATS
PNG = '.png'

# FOR BACKGROUND
KOSMO_BGD = 'Pictures/bg_kosmo/kosmo'
FIRST_FRAME = 1
LAST_FRAME = 40

# MUSIC LINKS
MENU_MUSIC = '1679007940657971.ogg'
SOUND_COLLUSION = 'Samples/3816133910831170.ogg'
SOUND_CLICK = 'Samples/zapsplat_multimedia_button_click_005_68777.mp3'
SAME_LINK_FOR_QUOTES = 'Quotes/quote'
PATH_FOR_CREATE_QUOTES = 'Music/Quotes/quote'
PATH_FOR_SOUND_IN_LEVELS = 'Music/Music for levels/'
SOUND_RESTART = 'Samples/8476647490550829.ogg'
PATH_MUSIC = 'Music/'

# MUSIC PARAMETRES
USING_VOLUME = 0.2
FORMAT_OGG = '.ogg'
INFINITY_PLAYBACK = -1

# PARSE LINKS
URL_FOR_QUOTE = 'https://api.quotable.io/random'
GET_QUOTE = 'content'

# LANGUAGE FOR TRANSLATE
RU = 'ru'
EN = 'en'

# DELAY VAlUES
DELAY_THREE_OO = 300
# CONSTS FOR SCREEN
SIZE = WIDTH, HEIGHT = 600, 800
START_OF_SCREEN = (0, 0)
FPS_SIXTY = 60
FPS_FIFTEEN = 15
NOT_UPDATE_Y_CORD_1 = -400
NOT_UPDATE_Y_CORD_2 = 1000
DODGE_Y_CORD = 600
ONE_PIX = 1

# CONSTS FOR MAKE IMG TRANSPARENT
SPECIAL_VALUE = -1

# CONSTS FOR CIRCLE TRACES
ANGLE_PI = 180
START_TRACE_RADIUS = 5
QUANTITY_TRACE_CIRCLES = 50
RADIUS_FOR_DELETE_TRACE = 0
NUM_FOR_DECREASE_RADIUS = 50
DECREASE_TRACE_RADIUS = 1
CONNECT_CIRCLE_WTH_TRC = 10
IMPOSSIBLE_SPEED = 0

# CONSTS FOR MOVEMENT CIRCLES
SPEED_MOVEMENT_TRUE = 5
SPEED_MOVEMENT_FALSE = -5
CONVERT_ANGLE_TO_SIDE = 100

# CONSTS FOR GRAY CIRCLE (along which the circles rotate)
GRAY_CIRCLE_POSITION = (300, 600)
GRAY_CIRCLE_RADIUS = 100
GRAY_CIRCLE_WIDTH = 1

# CONSTS FOR RED CIRCLE
RED_CIRCLE_START_ANGLE = 0
RED_CIRCLE_START_X = 385
RED_CIRCLE_START_Y = 585

# CONSTS FOR BLUE CIRCLE
BLUE_CIRCLE_START_ANGLE = 180
BLUE_CIRCLE_START_X = 185
BLUE_CIRCLE_START_Y = 585

# SAME CONSTS FOR CIRCLES
CHANGE_X_COORD = HEIGHT // 2 - 115
CHANGE_Y_COORD = HEIGHT - 215

# INDEXES FOR ALL OBSTACLES
INX_IMG_NAME = 0
INX_X_POS = 1
INX_Y_POS = 2
INX_X_SPEED = 3
INX_Y_SPEED = 4

# INDEXES FOR SLOWER TWIST OBSTACLE
INX_STEP_ANG_TWIST = 5
INX_BASE_ANG_TWIST = 6

# INDEXES FOR SLIDE SIDE AND LF_DOWN OBSTACLE
INX_STATIC_ANGLE = 5
BASE_X_MOVE = 0
BASE_Y_MOVE = 0
BASE_ANGLE_MOVE = 0

# INDEXES FOR SLIDE SIDE OBSTACLE
INX_Y_START_SIDE = 6
INX_Y_END_SIDE = 7
INX_STEP_SPEED_SIDE = 8

# INDEXES FOR LEFT RIGHT AND DOWN MOVING OBSTACLE
INX_Y_START_DOWN = 6
INX_Y_END_DOWN = 7
INX_STEP_SPEED_DOWN = 8
INX_LEFT_BOARD_LF = 9
INX_RIGHT_BOARD_LF = 10
INX_STEP_SPEED_LF = 11

# ARGS OF FRAMES FOR LEFT RIGHT MOVING
SIXTY_FRAMES = 60
LIMIT_FRAME = 20
ZERO_FRAMES = 0
STEP_FRAME = 1

# CHECK LEVEL COMPLETE
MAX_RECT_Y_IN_LEVEL = 1000

# VALUES FOR DATABASE
USERS = 'Users'
IMAGES = 'Images'
LEVELS = 'Levels'
LF_DOWN_OBSTACLES = 'LfDownObstacles'
SIDE_OBSTACLES = 'SideObstacles'
TWIST_OBSTACLES = 'TwistObstacles'

ID = 'id'
NAME = 'name'

ID_LEVEL = 'id_level'
ID_IMAGE = 'id_image'
X_POS = 'x_pos'
Y_POS = 'y_pos'
X_SPEED = 'x_speed'
Y_SPEED = 'y_speed'

Y_START_DOWN = 'y_start_down'
Y_END_DOWN = 'y_end_down'
SPEED_STEP_DOWN = 'speed_step_down'
LEFT_BOARD_LF = 'left_board_lf'
RIGHT_BOARD_LF = 'right_board_lf'
SPEED_STEP_LF = 'speed_step_lf'

ANGLE_STATIC = 'angle_static'
Y_START_SIDE = 'y_start_side'
Y_END_SIDE = 'y_end_side'
SPEED_STEP_SIDE = 'speed_step_side'

ANGLE_STEP = 'angle_step'
ANGLE_MOVE = 'angle_move'

MUS_LEVEL = 'music level'
SPEED = 'speed'
COINS = 'coins'
COINS_AMOUNT = 'coins_amount'

SETTINGS = 'settings'
EFFECTS = 'effects'
MUSIC = 'music'
MUSIC_LEVEL = 'music_level'
VOICE = 'voice'
SOUND_EFFECTS = 'sound_effects'
PICTURES = 'pictures/'
INF_LEVELS = 'Infinity_level_scores'
SCORE = 'score'
NAME_PLAYER = 'name_player'

TABLES = {
    IMAGES: [ID,
             NAME],
    USERS: [ID, COINS_AMOUNT],
    LEVELS: [ID, MUS_LEVEL, SPEED, COINS],

    LF_DOWN_OBSTACLES: [ID_LEVEL, ID_IMAGE,
                        X_POS, Y_POS,
                        X_SPEED, Y_SPEED, ANGLE_STATIC,
                        Y_START_DOWN,
                        Y_END_DOWN,
                        SPEED_STEP_DOWN,
                        LEFT_BOARD_LF,
                        RIGHT_BOARD_LF,
                        SPEED_STEP_LF],

    SIDE_OBSTACLES: [ID_LEVEL, ID_IMAGE,
                     X_POS, Y_POS,
                     X_SPEED, Y_SPEED,
                     ANGLE_STATIC,
                     Y_START_SIDE,
                     Y_END_SIDE,
                     SPEED_STEP_SIDE],

    TWIST_OBSTACLES: [ID_LEVEL, ID_IMAGE,
                      X_POS, Y_POS,
                      X_SPEED, Y_SPEED,
                      ANGLE_STEP,
                      ANGLE_MOVE]

}

# INDEXES FOR GET LEVEL'S OBSTACLES
INX_ID_LEVEL = 0
HIDDEN_OBSTACLE = True
INX_IMG_ID = 1

# INDEXES FOR CREATING WALLS
INX_INVIZ = 0
INX_INFO_ARRAY = 1
BASE_STATIC_ANGLE = 0

# LEVELS
ZERO_COINS = 0

ALL_LEVELS = []
for i in range(1, 7):
    for j in range(1, 7):
        ALL_LEVELS.append(int(str(i) + str(j)))

# MESSAGES
LEVEL_COMPLITED = 'Уровень пройден!'
PAUSE_ACTIONS = 'пауза, нажмите Enter, чтобы'
BANK_MESSAGE = 'Вы получаете:'
COIN_MESSAGE = 'монет'
DODGED_MESS = 'Dodged:'
TITLE = 'GLADE'
PLOT_TITLE = 'сюжет'
IGNORANCE_TITLE = 'незнание'
DENIAL_TITLE = 'отрицание'
ANGER_TITLE = 'гнев'
CONVERSATION_TITLE = 'переговоры'
HOPE_TITLE = 'надежда'
ACCEPTANCE_TITLE = 'принятие'
LEFT_KEY_NAME = 'LEFT'
RIGHT_KEY_NAME = 'RIGHT'
MANAGEMENT_TITLE = 'Управление'
EFFECTS_TITLE = 'эффекты'
RIGHT_TITLE = 'вправо'
LEFT_TITLE = 'влево'
ITEM_SHOP_TITLE = 'Магазин скинов'
MUSIC_SETTINGS = 'музыка - '
VOICE_SETTINGS = 'речь - '
SOUND_EFF_SETTINGS = 'звуковые эффекты - '
MESSAGE_BEFORE_START_GAME = f'Введите свое имя, чтобы начать игру'
TOP_PLAYER = 'Топ игрок(результат): '
# BUTTONS SIZE
BTN_RESUME_X = 150
BTN_RESUME_Y = 50
BTN_LEAVE_HUB_X = 150
BTN_LEAVE_HUB_Y = 50
BTN_LEVELS_X = 50
BTN_LEVELS_Y = 50

# BUTTONS TEXT
BTN_CONTINUE_TEXT = 'продолжить'
BTN_LEAVE_TEXT = 'выход'
PAUSE_BTN_TEXT = 'II'
BTN_SOUND_TEXT = 'звук'
BTN_BACK_TEXT = 'назад'
BTN_ON_TEXT = 'вкл'
BTN_OFF_TEXT = 'выкл'
BTN_NEXT_PAGE_TEXT = 'следующая страница'
BTN_SETTINGS_TEXT = 'настройки'
BTN_PLAY_TEXT = 'играть'
BTN_ITEM_SHOP_TEXT = 'магазин'
BTN_RACE_TEXT = 'гонка'
BTN_PLOT_TEXT = 'сюжет'
BTN_START_RACE = 'начать гонку'

# BUTTONS LEVELS
BTN_FIRST_LEVEL = ' I '
BTN_SECOND_LEVEL = 'II'
BTN_THIRD_LEVEL = 'III'
BTN_FOURTH_LEVEL = 'IV'
BTN_FIFTH_LEVEL = 'V'
BTN_SIXTH_LEVEL = 'VI'

# CONSTS FOR RENDER BORDERS
PADDING_DIST = 20
BORDER_WIDTH = 4
BORDER_LENGTH = 8

# CONSTS FOR INPUT PLAYER NAME
