# GENERAL
UNDEFINED = None

# DATABASE
DB_PATH = 'data/glide_db.db'

# TITLE OF GAME
TITLE = 'Glide game'

# COLORS (RGB)
BLACK_COLOR = (0, 0, 0)
RED_COLOR = (255, 0, 0)
BLUE_COLOR = (0, 0, 255)
DEEP_GRAY = (54, 54, 54)
WHITE_COLOR = (255, 255, 255)
RED_TRAIL_COLOR_1 = (255, 55, 0)
RED_TRAIL_COLOR_2 = (255, 85, 55)
RED_TRAIL_COLOR_3 = (255, 40, 40)
BLUE_TRAIL_COLOR_1 = (0, 170, 240)
BLUE_TRAIL_COLOR_2 = (15, 135, 255)
BLUE_TRAIL_COLOR_3 = (0, 190, 255)

# NAMES OF IMAGES
RED_CIRCLE_IMG = 'red_circle.png'
BLUE_CIRCLE_IMG = 'blue_circle.png'
BASE_WALL_IMG = "base_wall_2_1.png"

# CONSTS FOR SCREEN
SIZE = WIDTH, HEIGHT = 600, 800
FPS = 60

# CONSTS FOR CIRCLE TRACES
ANGLE_PI = 180
START_TRACE_RADIUS = 5
QUANTITY_TRACE_CIRCLES = 50
RADIUS_FOR_DELETE_TRACE = 0
NUM_FOR_DECREASE_RADIUS = 50
DECREASE_TRACE_RADIUS = 1
CONNECT_CIRCLE_WTH_TRC = 10
IMPOSSIBLE_SPEED = 0

# CONSTS FOR MOVEMENT CIRCLES
SPEED_MOVEMENT_TRUE = 5
SPEED_MOVEMENT_FALSE = -5
CONVERT_ANGLE_TO_SIDE = 100

# CONSTS FOR GRAY CIRCLE (along which the circles rotate)
GRAY_CIRCLE_POSITION = (300, 600)
GRAY_CIRCLE_RADIUS = 100
GRAY_CIRCLE_WIDTH = 1

# CONSTS FOR RED CIRCLE
RED_CIRCLE_START_ANGLE = 0
RED_CIRCLE_START_X = 385
RED_CIRCLE_START_Y = 585

# CONSTS FOR BLUE CIRCLE
BLUE_CIRCLE_START_ANGLE = 180
BLUE_CIRCLE_START_X = 185
BLUE_CIRCLE_START_Y = 585

# SAME CONSTS FOR CIRCLES
CHANGE_X_COORD = HEIGHT // 2 - 115
CHANGE_Y_COORD = HEIGHT - 215

# INDEXES FOR ALL OBSTACLE'S
INX_IMG_NAME = 0
INX_X_POS = 1
INX_Y_POS = 2
INX_X_SPEED = 3
INX_Y_SPEED = 4


# INDEXES FOR SLOWER TWIST OBSTACLE
INX_STEP_ANG_TWIST = 5
INX_BASE_ANG_TWIST = 6

# INDEXES FOR SLIDE SIDE AND LFDOWN OBSTACLE
INX_STATIC_ANGLE = 5
BASE_X_MOVE = 0
BASE_Y_MOVE = 0
BASE_ANGLE_MOVE = 0

# INDEXES FOR SLIDE SIDE OBSTACLE
INX_Y_START_SIDE = 6
INX_Y_END_SIDE = 7
INX_STEP_SPEED_SIDE = 8

# INDEXES FOR LEFT RIGHT AND DOWN MOVING OBSTACLE
INX_Y_START_DOWN = 6
INX_Y_END_DOWN = 7
INX_STEP_SPEED_DOWN = 8
INX_LEFT_BOARD_LF = 9
INX_RIGHT_BOARD_LF = 10
INX_STEP_SPEED_LF = 11

# ARGS OF FRAMES FOR LEFT RIGHT MOVING
SIXTY_FRAMES = 60
ZERO_FRAMES = 0
STEP_FRAME = 1
